# -*- coding: utf-8 -*-
"""4NI25CS192_EXP_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bnfhScdZfUJNwj91lwIky1SHN7BAsIpq
"""

import numpy as np
import pandas as pd
marks=np.array([75,85,95,88])
print("Marks:",marks)
print("Type:",type(marks))
print("Number of dimension:",marks.ndim)
print("Shape:",marks.shape)
print("Number of elements:",marks.size)

print("Original:",marks)
print("Add 5:",marks+5)

print("Sum:",marks.sum())
print("Mean:",marks.mean())
print("Maximum:",marks.max())

print("First marks:",marks[0])
print("Second marks:",marks[2])
print("Last marks:",marks[-1])

print("Index 1 to 3:",marks[1:4])
print("First three:",marks[:3])
print("From index 2:",marks[2:])

student_marks=np.array([
    [78,65,78],
    [56,89,90],
    [54,7,89]
])
print(student_marks)
print("Shape:",student_marks.shape)

print("First student:",student_marks[0])
print("Second student:",student_marks[1])
print("Third student:",student_marks[2])

data={
    "Name":["Anu","Rahul","Kiran","Priya"],
    "Branch":["CSE","AIML","CSE","AIML"],
    "Marks":[85,91,76,89]
}
df=pd.DataFrame(data)
df

print("Shape:",df.shape)
print("Column:",df.columns)

df.info()

df.tail()

df.describe()



print("First row:")
print(df.iloc[0])
print("Second row:\n",df.iloc[1])
print("First three row:\n",df.iloc[:3])
print("Last two row:\n",df.iloc[-2:])
print("First two row and first two columns:\n",df.iloc[:2,:2])

print("First three rows:\n",df.iloc[:3])
print("Rows 1 to 3,Name and Marks:",df.iloc[1:4,0:3])

high_marks=df[df["Marks"]>90]
print(high_marks)

print("Students from CSE:",df[df["Branch"]=="CSE"])
print("Students scoring 85 or above:",df[df["Marks"]>=85])

data={
    "Name":["Asha","Bharat","Chetan","Divya","Easha"],
    "Department":["CSE","ISE","CSE","AIML","ISE"],
    "Marks":[72,91,84,95,68],
    "Attendance":[82,94,88,96,75]
}
students=pd.DataFrame(data)
print(students)

print("name:",students["Name"])
print("Marks:",students["Marks"])

print("Students scored more than 80:",students[students["Marks"]>=80])

print("Students whose attendance is above 85:",students[students["Attendance"]>=85])

students.iloc[0:3]

students['Marks'].mean()

students['Marks'].max()

students[students["Department"]=="CSE"]

students[(students["Marks"]>=90)&(students["Attendance"]>85)]